name: Release Docs

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check_ref:
    name: Check tag targets main
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.check.outputs.on_main }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine if tag commit is on main
        id: check
        run: |
          git fetch origin main
          if git merge-base --is-ancestor "${GITHUB_SHA}" origin/main; then
            echo "on_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "on_main=false" >> "$GITHUB_OUTPUT"
          fi

  test:
    name: Build and Test
    runs-on: macos-15
    needs: check_ref
    if: needs.check_ref.outputs.on_main == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
      - name: Build (release)
        run: swift build -c release
      - name: Test (release)
        run: swift test -c release

  docs:
    name: Build DocC
    needs: test
    runs-on: macos-15
    if: needs.check_ref.outputs.on_main == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
      - name: Generate DocC (static site)
        run: |
          swift package --disable-sandbox \
            generate-documentation \
            --target SimpleOverlaySystem \
            --output-path docs \
            --transform-for-static-hosting \
            --hosting-base-path SimpleOverlaySystem
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    needs: docs
    runs-on: ubuntu-latest
    if: needs.check_ref.outputs.on_main == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
